### ISSUE TITLE
Navbar not closing

### ISSUE THREAD

**Issue by abhigyanghosh30** [zubairabid/megathon2018#13]
Navbar doesnot seem to close when clicked on in the landing section

**Comment by zubairabid** [comment]
@abhigyanghosh30 Meaning?

**Comment by abhigyanghosh30** [comment]
Try opening the navbar in mobile while on the landing image, the navbar doesnot close

**Comment by zubairabid** [comment]
@abhigyanghosh30 Right now it closes, only on swiping. We'll add a "close navbar" button. You can add it if you like
